file:C:/Program Files/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig	http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig	http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig	core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig	core.fscache=true
file:C:/Program Files/Git/etc/gitconfig	core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig	pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig	credential.helper=manager
file:C:/Program Files/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig	init.defaultbranch=master
file:"C:/Users/Alfredo Santiba\303\261ez/.gitconfig"	user.email=asantibanez@yahoo.com
file:"C:/Users/Alfredo Santiba\303\261ez/.gitconfig"	user.name=Alfredo Santibañez
file:"C:/Users/Alfredo Santiba\303\261ez/.gitconfig"	core.autocrlf=true
file:"C:/Users/Alfredo Santiba\303\261ez/.gitconfig"	http.sslverify=true
file:"C:/Users/Alfredo Santiba\303\261ez/.gitconfig"	credential.helper=manager
file:"C:/Users/Alfredo Santiba\303\261ez/.gitconfig"	credential.helper=manager-core
file:.git/config	core.bare=false
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	core.logallrefupdates=true
file:.git/config	user.name=Alfredo
file:.git/config	user.email=asantibanez@yahoo.com
file:.git/config	remote.origin.url=https://asantibanez62@bitbucket.org/alfredosantibanez/recibosbsc.git
